### ISSUE TITLE
MARA dependencies

### ISSUE THREAD

**Issue by nzlz** [erlerobot/HRIM#19]
After the last update of HRIM some dependencies required by [MARA](https://github.com/acutronicRobotics/MARA) have disappeared, making MARA unusable.

```
hrim_generic_msgs
hrim_actuator_rotaryservo_msgs
```

I will try to take a look at the new HRIM and update MARA. In the meantime, it would be a good idea to create a temporary branch (`mara`) with the previous version of HRIM.

**Comment by vmayoral** [comment]
@ahcorde and @ibaiape, please help wit this.

**Comment by nzlz** [comment]
Solved by reading the new README. I will update the MARA installation instructions asap.
