### ISSUE TITLE
Feature request: new release

### ISSUE THREAD

**Issue by vmayoral** [erlerobot/HRIM#23]
@ibaiape, @ahcorde, we spoke a while ago about the need to make another release of HRIM.

Once you finish with all the existing work we're doing, could we please make a new release, document it at https://acutronicrobotics.com/docs/technology/hrim and spread the word a bit?

**Comment by ahcorde** [comment]
I have created a new release called [Beriain](https://github.com/erlerobot/HRIM/releases) and @ibaiape has updated the [documentation](https://acutronicrobotics.com/docs/technology/hrim)

**Comment by ibaiape** [comment]
The documentation changes are the following:
 * Published hidden sensors (there were missing files).
 * Updated links to HRIM repository (from **xml** branch to **master**).
 * Added [tooling](https://acutronicrobotics.com/docs/technology/hrim/model/tooling) section. Makes reference to an older commit (before the deltion of the example implementation), so some things need to be updated, but mostly holds true.

Right now I'm working on implementing the meta-model, will document the release shortly.
